### ISSUE TITLE
click have this problem

### ISSUE THREAD

**Issue by guxiaonian** [shellljx/FuckingVolumeSlider#1]
java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet
    at com.example.anew.aa.VolumeSliderView.startUpAnimator(VolumeSliderView.java:202)
                                                                      at com.example.anew.aa.VolumeSliderView.onTouchEvent(VolumeSliderView.java:174)

**Comment by shellljx** [comment]
#f887745c424294e3bd376398a373c72b1a503edb

**Comment by shellljx** [comment]
fixed this bug
